
spring:
  application:
    name: hotel-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5572}/${DB_NAME:hotel}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:873240$348a}

  liquibase:
    enabled: true
    change-log: "classpath:/changelog/master.xml"
    driver-class-name: org.postgresql.Driver
    contexts: dev

server:
  port: 9068
